// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn739IB-rV_yt6_hZ2yk4NtwgEQqdmHuI',
    appId: '1:535390883975:android:01800db83f50701716a822',
    messagingSenderId: '535390883975',
    projectId: 'finfit-431b8',
    storageBucket: 'finfit-431b8.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3l-QjQpUe5CM8bSFUoNOg3IgYZwT3lIA',
    appId: '1:535390883975:web:7f91ceb656cdd20316a822',
    messagingSenderId: '535390883975',
    projectId: 'finfit-431b8',
    authDomain: 'finfit-431b8.firebaseapp.com',
    storageBucket: 'finfit-431b8.firebasestorage.app',
    measurementId: 'G-ZCX2F53MG5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn1pqhLq9unU3ZJqNodfQ_CYdU9zUxavI',
    appId: '1:535390883975:ios:f668af006ca7312216a822',
    messagingSenderId: '535390883975',
    projectId: 'finfit-431b8',
    storageBucket: 'finfit-431b8.firebasestorage.app',
    iosBundleId: 'com.example.finfit',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn1pqhLq9unU3ZJqNodfQ_CYdU9zUxavI',
    appId: '1:535390883975:ios:f668af006ca7312216a822',
    messagingSenderId: '535390883975',
    projectId: 'finfit-431b8',
    storageBucket: 'finfit-431b8.firebasestorage.app',
    iosBundleId: 'com.example.finfit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3l-QjQpUe5CM8bSFUoNOg3IgYZwT3lIA',
    appId: '1:535390883975:web:6bb1a526b280960416a822',
    messagingSenderId: '535390883975',
    projectId: 'finfit-431b8',
    authDomain: 'finfit-431b8.firebaseapp.com',
    storageBucket: 'finfit-431b8.firebasestorage.app',
    measurementId: 'G-BR0DCM6TN6',
  );

}